version: 1.0.{build}

branches:
  only:
  - master

install:
  - ps: Get-NodeJsLatestBuild 8.4
  - ps: Install-Product node 8.4.0 x64
  - node -v
  - cd %APPVEYOR_BUILD_FOLDER%
  - npm install npm@latest
  - npm install --save three three.ar.js

build: off

test: off